/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as DouyinRouteRouteImport } from './routes/douyin/route'
import { Route as BilibiliRouteRouteImport } from './routes/bilibili/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DouyinIndexRouteImport } from './routes/douyin/index'
import { Route as BilibiliIndexRouteImport } from './routes/bilibili/index'
import { Route as DouyinProfileRouteImport } from './routes/douyin/profile'
import { Route as DouyinHistoryRouteImport } from './routes/douyin/history'
import { Route as DouyinFavoriteRouteImport } from './routes/douyin/favorite'
import { Route as DouyinDownloadRouteImport } from './routes/douyin/download'
import { Route as BilibiliProfileRouteImport } from './routes/bilibili/profile'
import { Route as BilibiliHistoryRouteImport } from './routes/bilibili/history'
import { Route as BilibiliFavoriteRouteImport } from './routes/bilibili/favorite'
import { Route as BilibiliDownloadRouteImport } from './routes/bilibili/download'
import { Route as DouyinUserRouteRouteImport } from './routes/douyin/user/route'
import { Route as BilibiliUpRouteRouteImport } from './routes/bilibili/up/route'
import { Route as DouyinUserIndexRouteImport } from './routes/douyin/user/index'
import { Route as BilibiliUpIndexRouteImport } from './routes/bilibili/up/index'
import { Route as DouyinUserSecUserIdRouteImport } from './routes/douyin/user/$secUserId'
import { Route as BilibiliUpMidRouteImport } from './routes/bilibili/up/$mid'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DouyinRouteRoute = DouyinRouteRouteImport.update({
  id: '/douyin',
  path: '/douyin',
  getParentRoute: () => rootRouteImport,
} as any)
const BilibiliRouteRoute = BilibiliRouteRouteImport.update({
  id: '/bilibili',
  path: '/bilibili',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DouyinIndexRoute = DouyinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DouyinRouteRoute,
} as any)
const BilibiliIndexRoute = BilibiliIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const DouyinProfileRoute = DouyinProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DouyinRouteRoute,
} as any)
const DouyinHistoryRoute = DouyinHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => DouyinRouteRoute,
} as any)
const DouyinFavoriteRoute = DouyinFavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => DouyinRouteRoute,
} as any)
const DouyinDownloadRoute = DouyinDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => DouyinRouteRoute,
} as any)
const BilibiliProfileRoute = BilibiliProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliHistoryRoute = BilibiliHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliFavoriteRoute = BilibiliFavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const BilibiliDownloadRoute = BilibiliDownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const DouyinUserRouteRoute = DouyinUserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => DouyinRouteRoute,
} as any)
const BilibiliUpRouteRoute = BilibiliUpRouteRouteImport.update({
  id: '/up',
  path: '/up',
  getParentRoute: () => BilibiliRouteRoute,
} as any)
const DouyinUserIndexRoute = DouyinUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DouyinUserRouteRoute,
} as any)
const BilibiliUpIndexRoute = BilibiliUpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BilibiliUpRouteRoute,
} as any)
const DouyinUserSecUserIdRoute = DouyinUserSecUserIdRouteImport.update({
  id: '/$secUserId',
  path: '/$secUserId',
  getParentRoute: () => DouyinUserRouteRoute,
} as any)
const BilibiliUpMidRoute = BilibiliUpMidRouteImport.update({
  id: '/$mid',
  path: '/$mid',
  getParentRoute: () => BilibiliUpRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bilibili': typeof BilibiliRouteRouteWithChildren
  '/douyin': typeof DouyinRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/bilibili/up': typeof BilibiliUpRouteRouteWithChildren
  '/douyin/user': typeof DouyinUserRouteRouteWithChildren
  '/bilibili/download': typeof BilibiliDownloadRoute
  '/bilibili/favorite': typeof BilibiliFavoriteRoute
  '/bilibili/history': typeof BilibiliHistoryRoute
  '/bilibili/profile': typeof BilibiliProfileRoute
  '/douyin/download': typeof DouyinDownloadRoute
  '/douyin/favorite': typeof DouyinFavoriteRoute
  '/douyin/history': typeof DouyinHistoryRoute
  '/douyin/profile': typeof DouyinProfileRoute
  '/bilibili/': typeof BilibiliIndexRoute
  '/douyin/': typeof DouyinIndexRoute
  '/bilibili/up/$mid': typeof BilibiliUpMidRoute
  '/douyin/user/$secUserId': typeof DouyinUserSecUserIdRoute
  '/bilibili/up/': typeof BilibiliUpIndexRoute
  '/douyin/user/': typeof DouyinUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/bilibili/download': typeof BilibiliDownloadRoute
  '/bilibili/favorite': typeof BilibiliFavoriteRoute
  '/bilibili/history': typeof BilibiliHistoryRoute
  '/bilibili/profile': typeof BilibiliProfileRoute
  '/douyin/download': typeof DouyinDownloadRoute
  '/douyin/favorite': typeof DouyinFavoriteRoute
  '/douyin/history': typeof DouyinHistoryRoute
  '/douyin/profile': typeof DouyinProfileRoute
  '/bilibili': typeof BilibiliIndexRoute
  '/douyin': typeof DouyinIndexRoute
  '/bilibili/up/$mid': typeof BilibiliUpMidRoute
  '/douyin/user/$secUserId': typeof DouyinUserSecUserIdRoute
  '/bilibili/up': typeof BilibiliUpIndexRoute
  '/douyin/user': typeof DouyinUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bilibili': typeof BilibiliRouteRouteWithChildren
  '/douyin': typeof DouyinRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/bilibili/up': typeof BilibiliUpRouteRouteWithChildren
  '/douyin/user': typeof DouyinUserRouteRouteWithChildren
  '/bilibili/download': typeof BilibiliDownloadRoute
  '/bilibili/favorite': typeof BilibiliFavoriteRoute
  '/bilibili/history': typeof BilibiliHistoryRoute
  '/bilibili/profile': typeof BilibiliProfileRoute
  '/douyin/download': typeof DouyinDownloadRoute
  '/douyin/favorite': typeof DouyinFavoriteRoute
  '/douyin/history': typeof DouyinHistoryRoute
  '/douyin/profile': typeof DouyinProfileRoute
  '/bilibili/': typeof BilibiliIndexRoute
  '/douyin/': typeof DouyinIndexRoute
  '/bilibili/up/$mid': typeof BilibiliUpMidRoute
  '/douyin/user/$secUserId': typeof DouyinUserSecUserIdRoute
  '/bilibili/up/': typeof BilibiliUpIndexRoute
  '/douyin/user/': typeof DouyinUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bilibili'
    | '/douyin'
    | '/settings'
    | '/bilibili/up'
    | '/douyin/user'
    | '/bilibili/download'
    | '/bilibili/favorite'
    | '/bilibili/history'
    | '/bilibili/profile'
    | '/douyin/download'
    | '/douyin/favorite'
    | '/douyin/history'
    | '/douyin/profile'
    | '/bilibili/'
    | '/douyin/'
    | '/bilibili/up/$mid'
    | '/douyin/user/$secUserId'
    | '/bilibili/up/'
    | '/douyin/user/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/bilibili/download'
    | '/bilibili/favorite'
    | '/bilibili/history'
    | '/bilibili/profile'
    | '/douyin/download'
    | '/douyin/favorite'
    | '/douyin/history'
    | '/douyin/profile'
    | '/bilibili'
    | '/douyin'
    | '/bilibili/up/$mid'
    | '/douyin/user/$secUserId'
    | '/bilibili/up'
    | '/douyin/user'
  id:
    | '__root__'
    | '/'
    | '/bilibili'
    | '/douyin'
    | '/settings'
    | '/bilibili/up'
    | '/douyin/user'
    | '/bilibili/download'
    | '/bilibili/favorite'
    | '/bilibili/history'
    | '/bilibili/profile'
    | '/douyin/download'
    | '/douyin/favorite'
    | '/douyin/history'
    | '/douyin/profile'
    | '/bilibili/'
    | '/douyin/'
    | '/bilibili/up/$mid'
    | '/douyin/user/$secUserId'
    | '/bilibili/up/'
    | '/douyin/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BilibiliRouteRoute: typeof BilibiliRouteRouteWithChildren
  DouyinRouteRoute: typeof DouyinRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/douyin': {
      id: '/douyin'
      path: '/douyin'
      fullPath: '/douyin'
      preLoaderRoute: typeof DouyinRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bilibili': {
      id: '/bilibili'
      path: '/bilibili'
      fullPath: '/bilibili'
      preLoaderRoute: typeof BilibiliRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/douyin/': {
      id: '/douyin/'
      path: '/'
      fullPath: '/douyin/'
      preLoaderRoute: typeof DouyinIndexRouteImport
      parentRoute: typeof DouyinRouteRoute
    }
    '/bilibili/': {
      id: '/bilibili/'
      path: '/'
      fullPath: '/bilibili/'
      preLoaderRoute: typeof BilibiliIndexRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/douyin/profile': {
      id: '/douyin/profile'
      path: '/profile'
      fullPath: '/douyin/profile'
      preLoaderRoute: typeof DouyinProfileRouteImport
      parentRoute: typeof DouyinRouteRoute
    }
    '/douyin/history': {
      id: '/douyin/history'
      path: '/history'
      fullPath: '/douyin/history'
      preLoaderRoute: typeof DouyinHistoryRouteImport
      parentRoute: typeof DouyinRouteRoute
    }
    '/douyin/favorite': {
      id: '/douyin/favorite'
      path: '/favorite'
      fullPath: '/douyin/favorite'
      preLoaderRoute: typeof DouyinFavoriteRouteImport
      parentRoute: typeof DouyinRouteRoute
    }
    '/douyin/download': {
      id: '/douyin/download'
      path: '/download'
      fullPath: '/douyin/download'
      preLoaderRoute: typeof DouyinDownloadRouteImport
      parentRoute: typeof DouyinRouteRoute
    }
    '/bilibili/profile': {
      id: '/bilibili/profile'
      path: '/profile'
      fullPath: '/bilibili/profile'
      preLoaderRoute: typeof BilibiliProfileRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/history': {
      id: '/bilibili/history'
      path: '/history'
      fullPath: '/bilibili/history'
      preLoaderRoute: typeof BilibiliHistoryRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/favorite': {
      id: '/bilibili/favorite'
      path: '/favorite'
      fullPath: '/bilibili/favorite'
      preLoaderRoute: typeof BilibiliFavoriteRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/bilibili/download': {
      id: '/bilibili/download'
      path: '/download'
      fullPath: '/bilibili/download'
      preLoaderRoute: typeof BilibiliDownloadRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/douyin/user': {
      id: '/douyin/user'
      path: '/user'
      fullPath: '/douyin/user'
      preLoaderRoute: typeof DouyinUserRouteRouteImport
      parentRoute: typeof DouyinRouteRoute
    }
    '/bilibili/up': {
      id: '/bilibili/up'
      path: '/up'
      fullPath: '/bilibili/up'
      preLoaderRoute: typeof BilibiliUpRouteRouteImport
      parentRoute: typeof BilibiliRouteRoute
    }
    '/douyin/user/': {
      id: '/douyin/user/'
      path: '/'
      fullPath: '/douyin/user/'
      preLoaderRoute: typeof DouyinUserIndexRouteImport
      parentRoute: typeof DouyinUserRouteRoute
    }
    '/bilibili/up/': {
      id: '/bilibili/up/'
      path: '/'
      fullPath: '/bilibili/up/'
      preLoaderRoute: typeof BilibiliUpIndexRouteImport
      parentRoute: typeof BilibiliUpRouteRoute
    }
    '/douyin/user/$secUserId': {
      id: '/douyin/user/$secUserId'
      path: '/$secUserId'
      fullPath: '/douyin/user/$secUserId'
      preLoaderRoute: typeof DouyinUserSecUserIdRouteImport
      parentRoute: typeof DouyinUserRouteRoute
    }
    '/bilibili/up/$mid': {
      id: '/bilibili/up/$mid'
      path: '/$mid'
      fullPath: '/bilibili/up/$mid'
      preLoaderRoute: typeof BilibiliUpMidRouteImport
      parentRoute: typeof BilibiliUpRouteRoute
    }
  }
}

interface BilibiliUpRouteRouteChildren {
  BilibiliUpMidRoute: typeof BilibiliUpMidRoute
  BilibiliUpIndexRoute: typeof BilibiliUpIndexRoute
}

const BilibiliUpRouteRouteChildren: BilibiliUpRouteRouteChildren = {
  BilibiliUpMidRoute: BilibiliUpMidRoute,
  BilibiliUpIndexRoute: BilibiliUpIndexRoute,
}

const BilibiliUpRouteRouteWithChildren = BilibiliUpRouteRoute._addFileChildren(
  BilibiliUpRouteRouteChildren,
)

interface BilibiliRouteRouteChildren {
  BilibiliUpRouteRoute: typeof BilibiliUpRouteRouteWithChildren
  BilibiliDownloadRoute: typeof BilibiliDownloadRoute
  BilibiliFavoriteRoute: typeof BilibiliFavoriteRoute
  BilibiliHistoryRoute: typeof BilibiliHistoryRoute
  BilibiliProfileRoute: typeof BilibiliProfileRoute
  BilibiliIndexRoute: typeof BilibiliIndexRoute
}

const BilibiliRouteRouteChildren: BilibiliRouteRouteChildren = {
  BilibiliUpRouteRoute: BilibiliUpRouteRouteWithChildren,
  BilibiliDownloadRoute: BilibiliDownloadRoute,
  BilibiliFavoriteRoute: BilibiliFavoriteRoute,
  BilibiliHistoryRoute: BilibiliHistoryRoute,
  BilibiliProfileRoute: BilibiliProfileRoute,
  BilibiliIndexRoute: BilibiliIndexRoute,
}

const BilibiliRouteRouteWithChildren = BilibiliRouteRoute._addFileChildren(
  BilibiliRouteRouteChildren,
)

interface DouyinUserRouteRouteChildren {
  DouyinUserSecUserIdRoute: typeof DouyinUserSecUserIdRoute
  DouyinUserIndexRoute: typeof DouyinUserIndexRoute
}

const DouyinUserRouteRouteChildren: DouyinUserRouteRouteChildren = {
  DouyinUserSecUserIdRoute: DouyinUserSecUserIdRoute,
  DouyinUserIndexRoute: DouyinUserIndexRoute,
}

const DouyinUserRouteRouteWithChildren = DouyinUserRouteRoute._addFileChildren(
  DouyinUserRouteRouteChildren,
)

interface DouyinRouteRouteChildren {
  DouyinUserRouteRoute: typeof DouyinUserRouteRouteWithChildren
  DouyinDownloadRoute: typeof DouyinDownloadRoute
  DouyinFavoriteRoute: typeof DouyinFavoriteRoute
  DouyinHistoryRoute: typeof DouyinHistoryRoute
  DouyinProfileRoute: typeof DouyinProfileRoute
  DouyinIndexRoute: typeof DouyinIndexRoute
}

const DouyinRouteRouteChildren: DouyinRouteRouteChildren = {
  DouyinUserRouteRoute: DouyinUserRouteRouteWithChildren,
  DouyinDownloadRoute: DouyinDownloadRoute,
  DouyinFavoriteRoute: DouyinFavoriteRoute,
  DouyinHistoryRoute: DouyinHistoryRoute,
  DouyinProfileRoute: DouyinProfileRoute,
  DouyinIndexRoute: DouyinIndexRoute,
}

const DouyinRouteRouteWithChildren = DouyinRouteRoute._addFileChildren(
  DouyinRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BilibiliRouteRoute: BilibiliRouteRouteWithChildren,
  DouyinRouteRoute: DouyinRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
