// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup(arg1, arg2) {
  return window['go']['utils']['Settings']['Backup'](arg1, arg2);
}

export function BanNamespace(arg1) {
  return window['go']['utils']['Settings']['BanNamespace'](arg1);
}

export function BannedNamespaces() {
  return window['go']['utils']['Settings']['BannedNamespaces']();
}

export function BlockCacheMetrics() {
  return window['go']['utils']['Settings']['BlockCacheMetrics']();
}

export function CacheMaxCost(arg1, arg2) {
  return window['go']['utils']['Settings']['CacheMaxCost'](arg1, arg2);
}

export function Close() {
  return window['go']['utils']['Settings']['Close']();
}

export function DropAll() {
  return window['go']['utils']['Settings']['DropAll']();
}

export function DropPrefix(arg1) {
  return window['go']['utils']['Settings']['DropPrefix'](arg1);
}

export function EstimateSize(arg1) {
  return window['go']['utils']['Settings']['EstimateSize'](arg1);
}

export function Flatten(arg1) {
  return window['go']['utils']['Settings']['Flatten'](arg1);
}

export function GetKey(arg1) {
  return window['go']['utils']['Settings']['GetKey'](arg1);
}

export function GetMergeOperator(arg1, arg2, arg3) {
  return window['go']['utils']['Settings']['GetMergeOperator'](arg1, arg2, arg3);
}

export function GetSavePreference() {
  return window['go']['utils']['Settings']['GetSavePreference']();
}

export function GetSequence(arg1, arg2) {
  return window['go']['utils']['Settings']['GetSequence'](arg1, arg2);
}

export function GetSleepTime() {
  return window['go']['utils']['Settings']['GetSleepTime']();
}

export function GetStorage() {
  return window['go']['utils']['Settings']['GetStorage']();
}

export function GetTheme() {
  return window['go']['utils']['Settings']['GetTheme']();
}

export function IndexCacheMetrics() {
  return window['go']['utils']['Settings']['IndexCacheMetrics']();
}

export function IsClosed() {
  return window['go']['utils']['Settings']['IsClosed']();
}

export function Levels() {
  return window['go']['utils']['Settings']['Levels']();
}

export function LevelsToString() {
  return window['go']['utils']['Settings']['LevelsToString']();
}

export function Load(arg1, arg2) {
  return window['go']['utils']['Settings']['Load'](arg1, arg2);
}

export function MaxBatchCount() {
  return window['go']['utils']['Settings']['MaxBatchCount']();
}

export function MaxBatchSize() {
  return window['go']['utils']['Settings']['MaxBatchSize']();
}

export function MaxVersion() {
  return window['go']['utils']['Settings']['MaxVersion']();
}

export function NewKVLoader(arg1) {
  return window['go']['utils']['Settings']['NewKVLoader'](arg1);
}

export function NewManagedWriteBatch() {
  return window['go']['utils']['Settings']['NewManagedWriteBatch']();
}

export function NewStream() {
  return window['go']['utils']['Settings']['NewStream']();
}

export function NewStreamAt(arg1) {
  return window['go']['utils']['Settings']['NewStreamAt'](arg1);
}

export function NewStreamWriter() {
  return window['go']['utils']['Settings']['NewStreamWriter']();
}

export function NewTransaction(arg1) {
  return window['go']['utils']['Settings']['NewTransaction'](arg1);
}

export function NewTransactionAt(arg1, arg2) {
  return window['go']['utils']['Settings']['NewTransactionAt'](arg1, arg2);
}

export function NewWriteBatch() {
  return window['go']['utils']['Settings']['NewWriteBatch']();
}

export function NewWriteBatchAt(arg1) {
  return window['go']['utils']['Settings']['NewWriteBatchAt'](arg1);
}

export function Opts() {
  return window['go']['utils']['Settings']['Opts']();
}

export function PrintHistogram(arg1) {
  return window['go']['utils']['Settings']['PrintHistogram'](arg1);
}

export function Ranges(arg1, arg2) {
  return window['go']['utils']['Settings']['Ranges'](arg1, arg2);
}

export function RunValueLogGC(arg1) {
  return window['go']['utils']['Settings']['RunValueLogGC'](arg1);
}

export function SetDiscardTs(arg1) {
  return window['go']['utils']['Settings']['SetDiscardTs'](arg1);
}

export function SetKey(arg1, arg2) {
  return window['go']['utils']['Settings']['SetKey'](arg1, arg2);
}

export function SetSavePreference(arg1) {
  return window['go']['utils']['Settings']['SetSavePreference'](arg1);
}

export function SetSleepTime(arg1) {
  return window['go']['utils']['Settings']['SetSleepTime'](arg1);
}

export function SetStorage(arg1) {
  return window['go']['utils']['Settings']['SetStorage'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['utils']['Settings']['SetTheme'](arg1);
}

export function Size() {
  return window['go']['utils']['Settings']['Size']();
}

export function StreamDB(arg1) {
  return window['go']['utils']['Settings']['StreamDB'](arg1);
}

export function Subscribe(arg1, arg2, arg3) {
  return window['go']['utils']['Settings']['Subscribe'](arg1, arg2, arg3);
}

export function Sync() {
  return window['go']['utils']['Settings']['Sync']();
}

export function Tables() {
  return window['go']['utils']['Settings']['Tables']();
}

export function Update(arg1) {
  return window['go']['utils']['Settings']['Update'](arg1);
}

export function VerifyChecksum() {
  return window['go']['utils']['Settings']['VerifyChecksum']();
}

export function View(arg1) {
  return window['go']['utils']['Settings']['View'](arg1);
}
