// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetStorage():Promise<string>;

export function GetTheme():Promise<string>;

export function SetStorage(arg1:context.Context):Promise<string>;

export function SetTheme(arg1:string):Promise<void>;
