// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {io} from '../models';
import {ristretto} from '../models';
import {badger} from '../models';
import {time} from '../models';
import {context} from '../models';
import {pb} from '../models';

export function Backup(arg1:io.Writer,arg2:number):Promise<number>;

export function BanNamespace(arg1:number):Promise<void>;

export function BannedNamespaces():Promise<Array<number>>;

export function BlockCacheMetrics():Promise<ristretto.Metrics>;

export function CacheMaxCost(arg1:badger.CacheType,arg2:number):Promise<number>;

export function Close():Promise<void>;

export function DropAll():Promise<void>;

export function DropPrefix(arg1:Array<any>):Promise<void>;

export function EstimateSize(arg1:Array<number>):Promise<number|number>;

export function Flatten(arg1:number):Promise<void>;

export function GetKey(arg1:string):Promise<string>;

export function GetMergeOperator(arg1:Array<number>,arg2:badger.MergeFunc,arg3:time.Duration):Promise<badger.MergeOperator>;

export function GetSavePreference():Promise<boolean>;

export function GetSequence(arg1:Array<number>,arg2:number):Promise<badger.Sequence>;

export function GetSleepTime():Promise<number>;

export function GetStorage():Promise<string>;

export function GetTheme():Promise<string>;

export function IndexCacheMetrics():Promise<ristretto.Metrics>;

export function IsClosed():Promise<boolean>;

export function Levels():Promise<Array<badger.LevelInfo>>;

export function LevelsToString():Promise<string>;

export function Load(arg1:io.Reader,arg2:number):Promise<void>;

export function MaxBatchCount():Promise<number>;

export function MaxBatchSize():Promise<number>;

export function MaxVersion():Promise<number>;

export function NewKVLoader(arg1:number):Promise<badger.KVLoader>;

export function NewManagedWriteBatch():Promise<badger.WriteBatch>;

export function NewStream():Promise<badger.Stream>;

export function NewStreamAt(arg1:number):Promise<badger.Stream>;

export function NewStreamWriter():Promise<badger.StreamWriter>;

export function NewTransaction(arg1:boolean):Promise<badger.Txn>;

export function NewTransactionAt(arg1:number,arg2:boolean):Promise<badger.Txn>;

export function NewWriteBatch():Promise<badger.WriteBatch>;

export function NewWriteBatchAt(arg1:number):Promise<badger.WriteBatch>;

export function Opts():Promise<badger.Options>;

export function PrintHistogram(arg1:Array<number>):Promise<void>;

export function Ranges(arg1:Array<number>,arg2:number):Promise<Array<badger.keyRange>>;

export function RunValueLogGC(arg1:number):Promise<void>;

export function SetDiscardTs(arg1:number):Promise<void>;

export function SetKey(arg1:string,arg2:string):Promise<void>;

export function SetSavePreference(arg1:boolean):Promise<void>;

export function SetSleepTime(arg1:number):Promise<void>;

export function SetStorage(arg1:context.Context):Promise<string>;

export function SetTheme(arg1:string):Promise<void>;

export function Size():Promise<number|number>;

export function StreamDB(arg1:badger.Options):Promise<void>;

export function Subscribe(arg1:context.Context,arg2:any,arg3:Array<pb.Match>):Promise<void>;

export function Sync():Promise<void>;

export function Tables():Promise<Array<badger.TableInfo>>;

export function Update(arg1:any):Promise<void>;

export function VerifyChecksum():Promise<void>;

export function View(arg1:any):Promise<void>;
