// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Collection(arg1, arg2) {
  return window['go']['api']['BiliBili']['Collection'](arg1, arg2);
}

export function CollectionItem(arg1, arg2, arg3) {
  return window['go']['api']['BiliBili']['CollectionItem'](arg1, arg2, arg3);
}

export function DownloadHistory() {
  return window['go']['api']['BiliBili']['DownloadHistory']();
}

export function DownloadVideoByDash(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['api']['BiliBili']['DownloadVideoByDash'](arg1, arg2, arg3, arg4, arg5);
}

export function DownloadVideosByDash(arg1) {
  return window['go']['api']['BiliBili']['DownloadVideosByDash'](arg1);
}

export function Favorites(arg1, arg2, arg3) {
  return window['go']['api']['BiliBili']['Favorites'](arg1, arg2, arg3);
}

export function FavoritesList() {
  return window['go']['api']['BiliBili']['FavoritesList']();
}

export function FollowList(arg1, arg2) {
  return window['go']['api']['BiliBili']['FollowList'](arg1, arg2);
}

export function Info(arg1) {
  return window['go']['api']['BiliBili']['Info'](arg1);
}

export function IsLoggedIn() {
  return window['go']['api']['BiliBili']['IsLoggedIn']();
}

export function IsRefresh() {
  return window['go']['api']['BiliBili']['IsRefresh']();
}

export function LogOut() {
  return window['go']['api']['BiliBili']['LogOut']();
}

export function MyInfo() {
  return window['go']['api']['BiliBili']['MyInfo']();
}

export function PollQRCode(arg1) {
  return window['go']['api']['BiliBili']['PollQRCode'](arg1);
}

export function QRCode() {
  return window['go']['api']['BiliBili']['QRCode']();
}

export function SeasonsArchivesList(arg1, arg2, arg3, arg4) {
  return window['go']['api']['BiliBili']['SeasonsArchivesList'](arg1, arg2, arg3, arg4);
}

export function SeasonsSeriesList(arg1, arg2, arg3) {
  return window['go']['api']['BiliBili']['SeasonsSeriesList'](arg1, arg2, arg3);
}

export function SeriesList(arg1, arg2, arg3, arg4) {
  return window['go']['api']['BiliBili']['SeriesList'](arg1, arg2, arg3, arg4);
}

export function VideoDetailConcise(arg1) {
  return window['go']['api']['BiliBili']['VideoDetailConcise'](arg1);
}

export function VideoDetailConciseBvid(arg1) {
  return window['go']['api']['BiliBili']['VideoDetailConciseBvid'](arg1);
}

export function VideoList(arg1, arg2, arg3) {
  return window['go']['api']['BiliBili']['VideoList'](arg1, arg2, arg3);
}

export function VideoPlayURL(arg1, arg2, arg3, arg4) {
  return window['go']['api']['BiliBili']['VideoPlayURL'](arg1, arg2, arg3, arg4);
}
