// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {api} from '../models';

export function Collection(arg1:number,arg2:number):Promise<model.CollectionData>;

export function CollectionItem(arg1:string,arg2:number,arg3:number):Promise<model.CollectionItemData>;

export function DownloadHistory():Promise<Array<api.DownloadHistoryItem>>;

export function DownloadVideoByDash(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DownloadVideosByDash(arg1:Array<api.DashDownloadTask>):Promise<api.DashDownloadBatchResult>;

export function Favorites(arg1:number,arg2:number,arg3:number):Promise<model.FavoriteData>;

export function FavoritesList():Promise<model.FavoritesData>;

export function FollowList(arg1:number,arg2:number):Promise<model.FollowData>;

export function Info(arg1:string):Promise<model.UserInfoData>;

export function IsLoggedIn():Promise<boolean>;

export function IsRefresh():Promise<model.RefreshData>;

export function LogOut():Promise<model.LogOut>;

export function MyInfo():Promise<model.MyInfoProfile>;

export function PollQRCode(arg1:string):Promise<model.PollQRCodeData>;

export function QRCode():Promise<model.QRCodeData>;

export function SeasonsArchivesList(arg1:string,arg2:number,arg3:number,arg4:number):Promise<model.SeasonsArchivesData>;

export function SeasonsSeriesList(arg1:string,arg2:number,arg3:number):Promise<model.SeasonsSeriesData>;

export function SeriesList(arg1:string,arg2:number,arg3:number,arg4:number):Promise<model.SeriesArchivesData>;

export function VideoDetailConcise(arg1:number):Promise<model.VideoDetailConciseData>;

export function VideoDetailConciseBvid(arg1:string):Promise<model.VideoDetailConciseData>;

export function VideoList(arg1:number,arg2:number,arg3:number):Promise<model.VideoListData>;

export function VideoPlayURL(arg1:number,arg2:string,arg3:number,arg4:number):Promise<model.VideoURLData>;
