// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearDownloadHistory() {
  return window['go']['api']['Douyin']['ClearDownloadHistory']();
}

export function CollectList(arg1) {
  return window['go']['api']['Douyin']['CollectList'](arg1);
}

export function Collection(arg1, arg2) {
  return window['go']['api']['Douyin']['Collection'](arg1, arg2);
}

export function CollectionList(arg1, arg2, arg3, arg4) {
  return window['go']['api']['Douyin']['CollectionList'](arg1, arg2, arg3, arg4);
}

export function DeleteDownloadHistory(arg1) {
  return window['go']['api']['Douyin']['DeleteDownloadHistory'](arg1);
}

export function Download(arg1) {
  return window['go']['api']['Douyin']['Download'](arg1);
}

export function DownloadHistory() {
  return window['go']['api']['Douyin']['DownloadHistory']();
}

export function DownloadVideos(arg1) {
  return window['go']['api']['Douyin']['DownloadVideos'](arg1);
}

export function FavoriteVideo(arg1, arg2) {
  return window['go']['api']['Douyin']['FavoriteVideo'](arg1, arg2);
}

export function FavoritesVideoList(arg1, arg2, arg3) {
  return window['go']['api']['Douyin']['FavoritesVideoList'](arg1, arg2, arg3);
}

export function FollowList(arg1) {
  return window['go']['api']['Douyin']['FollowList'](arg1);
}

export function GetCookie() {
  return window['go']['api']['Douyin']['GetCookie']();
}

export function ParseSecUserID(arg1) {
  return window['go']['api']['Douyin']['ParseSecUserID'](arg1);
}

export function ParseVideo(arg1) {
  return window['go']['api']['Douyin']['ParseVideo'](arg1);
}

export function Profile() {
  return window['go']['api']['Douyin']['Profile']();
}

export function SetCookie(arg1) {
  return window['go']['api']['Douyin']['SetCookie'](arg1);
}

export function User(arg1) {
  return window['go']['api']['Douyin']['User'](arg1);
}

export function UserSeries(arg1, arg2, arg3) {
  return window['go']['api']['Douyin']['UserSeries'](arg1, arg2, arg3);
}

export function UserVideoList(arg1, arg2, arg3) {
  return window['go']['api']['Douyin']['UserVideoList'](arg1, arg2, arg3);
}

export function VideoDetail(arg1) {
  return window['go']['api']['Douyin']['VideoDetail'](arg1);
}
