// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {api} from '../models';

export function ClearDownloadHistory():Promise<void>;

export function CollectList(arg1:number):Promise<model.CollectListResponse>;

export function Collection(arg1:number,arg2:number):Promise<model.CollectionResponse>;

export function CollectionList(arg1:string,arg2:string,arg3:number,arg4:number):Promise<model.CollectionListResponse>;

export function DeleteDownloadHistory(arg1:string):Promise<void>;

export function Download(arg1:string):Promise<void>;

export function DownloadHistory():Promise<Array<api.DouyinDownloadHistoryItem>>;

export function DownloadVideos(arg1:Array<api.DouyinDownloadTask>):Promise<api.DouyinDownloadBatchResult>;

export function FavoriteVideo(arg1:number,arg2:number):Promise<model.FavoriteVideoResponse>;

export function FavoritesVideoList(arg1:string,arg2:number,arg3:number):Promise<model.FavoriteVideoResponse>;

export function FollowList(arg1:number):Promise<model.FollowResponse>;

export function GetCookie():Promise<string>;

export function ParseSecUserID(arg1:string):Promise<string>;

export function ParseVideo(arg1:string):Promise<string>;

export function Profile():Promise<model.MyInfoResponse>;

export function SetCookie(arg1:string):Promise<void>;

export function User(arg1:string):Promise<model.UserResponse>;

export function UserSeries(arg1:string,arg2:number,arg3:number):Promise<model.UserSeriesResponse>;

export function UserVideoList(arg1:string,arg2:number,arg3:number):Promise<model.UserVideoListResponse>;

export function VideoDetail(arg1:string):Promise<model.VideoDetailResponse>;
